version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: password
    volumes:
      - vol_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL:    pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - vol_pgadmin:/var/lib/pgadmin

volumes:
  vol_pgdata:
  vol_pgadmin:
